### ISSUE TITLE
Emoji合成不能正常工作

### ISSUE THREAD

**Issue by Suli1337** [cssxsh/meme-helper#13]
![image](https://github.com/cssxsh/meme-helper/assets/85695579/91534cdb-41c7-4588-a52e-ced3f57d5a21)
![image](https://github.com/cssxsh/meme-helper/assets/85695579/e0d11098-ba06-4f75-bdcc-56f6e24e68ed)
是网络环境的问题吗？

**Comment by cssxsh** [comment]
https://github.com/xsalazar/emoji-kitchen/commit/ce84ddc4b2eb9179e6b46c3addb6eedc5d780e27

上游取消提供 emojiOutput.json

**Comment by Suli1337** [comment]
ok 明白

**Comment by Fish-LP** [comment]
上游文件似乎已经删除
