### ISSUE TITLE
choyen功能中文显示为方框

### ISSUE THREAD

**Issue by pilgrim773** [cssxsh/meme-helper#8]
![_OKYX 9A3_4_2PX0EMIZVTM](https://user-images.githubusercontent.com/13644483/219089988-b898da8b-7317-43fb-b0d9-1d16c781f749.png)
应该修改哪里的编码设置，还是跟前置插件有关系么

**Comment by cssxsh** [comment]
缺字体，你是不是第一次启动的时候字体没下载全？
`data/xyz.cssxsh.mirai.plugin.mirai-skia-plugin/fonts`

**Comment by pilgrim773** [comment]
这两个插件放进来启动的时候确实报错了一大堆，没有一个个挑出来看，最后也启动了。需要哪个字体我自行去下载一个吧

**Comment by cssxsh** [comment]
> 这两个插件放进来启动的时候确实报错了一大堆，没有一个个挑出来看，最后也启动了。需要哪个字体我自行去下载一个吧

理论上随便任意中文字体都行

**Comment by pilgrim773** [comment]
![image](https://user-images.githubusercontent.com/13644483/219363785-718f0a3a-9531-4aa6-a491-e067dfd2d4e2.png)
data/xyz.cssxsh.mirai.plugin.mirai-skia-plugin/fonts 下有中文字体

**Comment by cssxsh** [comment]
> ![image](https://user-images.githubusercontent.com/13644483/219363785-718f0a3a-9531-4aa6-a491-e067dfd2d4e2.png) data/xyz.cssxsh.mirai.plugin.mirai-skia-plugin/fonts 下有中文字体

你是 linux 系统吗
linux 系统下可能不会优先使用中文字体，导致没有使用fonts中的字体
`Noto Sans SC`, `Noto Serif SC` 这两个是我设计的时候使用的默认字体，本来如果找不到他们应该找其他已载入的中文的
因为太大了我换成了别的
你可以到网上找一下 放到 fonts

**Comment by pilgrim773** [comment]
那有没有办法让插件直接使用这些字体，就不重新下别的了
我是还在用centos

**Comment by cssxsh** [comment]
> 那有没有办法让插件直接使用这些字体，就不重新下别的了 我是还在用centos

那得等 `mirai-skia-plugin` 下个版本里我再修复了

**Comment by pilgrim773** [comment]
> Refere

那我也去下一个字体先试试 ，读取字体应该要重启吧

**Comment by pilgrim773** [comment]
以安装字体解决
